server {
  listen 80;
  charset utf-8;
  root /usr/share/nginx/html;
  index index.html;

  location /api/ {
    proxy_pass https://p01--create-api--kkj9gmg9xdcp.code.run;
    proxy_set_header X-Request-ID $request_id;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
