<script setup lang="ts">
import { reactive, ref } from 'vue'
import { applicationEntryApi } from '../api/applicationEntryApi'
const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei'}).format(new Date())
const form=reactive({applicationNo:'',applicationDate:today,channelCode:'WEB',productCode:'LIFE-DEMO',productVersion:'1.0',currencyCode:'TWD',sumAssuredAmount:'1000000.0000',premiumAmount:'12000.0000',paymentModeCode:'ANNUAL',requestedEffectiveDate:today})
const loading=ref(false),message=ref<string|null>(null),error=ref<string|null>(null)
async function submit(){loading.value=true;message.value=null;error.value=null;try{const result=await applicationEntryApi.create(form);message.value=`要保書 ${result.applicationNo} 已建立，應繳 ${result.currencyCode} ${result.calculatedPremiumAmount}`;form.applicationNo=''}catch(e){error.value=e instanceof Error?e.message:'建立失敗'}finally{loading.value=false}}
</script>
<template><section class="content-page"><header class="page-header"><div><p class="eyebrow">NEW BUSINESS</p><h2>新契約保單登打</h2><p>建立要保案件與首期應繳資料，後續接續繳費配對及核保批次。</p></div><span class="status-chip">狀態：送件</span></header>
<form class="panel" @submit.prevent="submit"><div class="panel-title"><h3>要保基本資料</h3><small>＊為必填欄位</small></div><div class="field-grid">
<label>要保書號碼＊<input v-model.trim="form.applicationNo" maxlength="32" required placeholder="例：NC-20260808-001"></label><label>要保日期＊<input v-model="form.applicationDate" type="date" required></label><label>通路＊<select v-model="form.channelCode"><option value="WEB">網路</option><option value="AGENT">業務員</option><option value="BANK">銀行通路</option></select></label><label>商品代碼＊<input v-model.trim="form.productCode" maxlength="32" required></label><label>商品版本＊<input v-model.trim="form.productVersion" maxlength="32" required></label><label>幣別＊<select v-model="form.currencyCode"><option value="TWD">TWD 新臺幣</option><option value="USD">USD 美元</option></select></label><label>保險金額＊<input v-model="form.sumAssuredAmount" inputmode="decimal" required></label><label>首期保費＊<input v-model="form.premiumAmount" inputmode="decimal" required></label><label>繳別＊<select v-model="form.paymentModeCode"><option value="ANNUAL">年繳</option><option value="SEMI_ANNUAL">半年繳</option><option value="QUARTERLY">季繳</option><option value="MONTHLY">月繳</option></select></label><label>預定生效日＊<input v-model="form.requestedEffectiveDate" type="date" required></label></div><div class="form-actions"><button class="primary-button" :disabled="loading">{{loading?'建立中…':'建立要保案件'}}</button></div></form><p v-if="message" class="status-message success">{{message}}</p><p v-if="error" class="status-message error">{{error}}</p></section></template>
