<script setup lang="ts">
import { reactive,ref } from 'vue'
import { customerApi } from '../api/customerApi'
const form=reactive({identityTypeCode:'NATIONAL_ID',identityNo:'',customerName:'',genderCode:'',birthDate:'',nationalityCode:'TW',residencyCountryCode:'TW',mobilePhone:'',email:'',postalCode:'',contactAddress:'',occupationCode:'',sourceOfFundsCode:'SALARY',insurancePurposeCode:'PROTECTION',consentVersion:'2026-01'})
const consent=ref(false),loading=ref(false),message=ref<string|null>(null),error=ref<string|null>(null)
async function submit(){loading.value=true;message.value=null;error.value=null;try{const result=await customerApi.create(form);message.value=`客戶 ${result.customerName} 已建立，客戶編號：${result.customerId}，證號：${result.maskedIdentityNo}`;form.identityNo='';form.customerName=''}catch(e){error.value=e instanceof Error?e.message:'客戶建立失敗'}finally{loading.value=false}}
</script>
<template><section class="content-page"><header class="page-header"><div><p class="eyebrow">CUSTOMER 360</p><h2>客戶資料建立</h2><p>姓名僅由客戶主檔維護；身分證、聯絡方式及地址採加密保存。</p></div><span class="status-chip">自然人</span></header><form class="panel" @submit.prevent="submit"><div class="panel-title"><h3>身分與基本資料</h3><small>＊為必填欄位</small></div><div class="field-grid">
<label>證件類型＊<select v-model="form.identityTypeCode"><option value="NATIONAL_ID">國民身分證</option><option value="RESIDENT_CERTIFICATE">居留證</option><option value="PASSPORT">護照</option></select></label><label>證件號碼＊<input v-model.trim="form.identityNo" maxlength="20" autocomplete="off" required></label><label>姓名＊<input v-model.trim="form.customerName" maxlength="100" required></label><label>性別＊<select v-model="form.genderCode" required><option value="" disabled>請選擇</option><option value="M">男性</option><option value="F">女性</option><option value="X">其他／未指定</option></select></label><label>出生日期＊<input v-model="form.birthDate" type="date" required></label><label>國籍＊<input v-model.trim="form.nationalityCode" maxlength="2" required></label><label>居住國家＊<input v-model.trim="form.residencyCountryCode" maxlength="2" required></label><label>行動電話＊<input v-model.trim="form.mobilePhone" maxlength="30" autocomplete="off" required></label><label>電子郵件＊<input v-model.trim="form.email" type="email" maxlength="254" autocomplete="off" required></label><label>郵遞區號＊<input v-model.trim="form.postalCode" maxlength="10" required></label><label class="wide-field">通訊地址＊<input v-model.trim="form.contactAddress" maxlength="300" autocomplete="off" required></label></div>
<div class="panel-title section-gap"><h3>KYC 基本資料</h3></div><div class="field-grid"><label>職業代碼＊<input v-model.trim="form.occupationCode" maxlength="32" required placeholder="例：OFFICE_WORKER"></label><label>資金來源＊<select v-model="form.sourceOfFundsCode"><option value="SALARY">薪資所得</option><option value="SAVINGS">儲蓄</option><option value="INVESTMENT">投資所得</option><option value="OTHER">其他</option></select></label><label>投保目的＊<select v-model="form.insurancePurposeCode"><option value="PROTECTION">保障需求</option><option value="RETIREMENT">退休規劃</option><option value="EDUCATION">教育準備</option><option value="OTHER">其他</option></select></label></div>
<label class="consent-row"><input v-model="consent" type="checkbox" required>已取得客戶個人資料蒐集、處理及利用同意</label><div class="form-actions"><button class="primary-button" :disabled="loading||!consent">{{loading?'建立中…':'建立客戶資料'}}</button></div></form><p v-if="message" class="status-message success">{{message}}</p><p v-if="error" class="status-message error">{{error}}</p></section></template>
