<script setup lang="ts">
import { computed, ref } from 'vue'
import { premiumPaymentApi } from '../api/premiumPaymentApi'
import type { PremiumDuePreview } from '../types/premiumPayment'
const applicationNo=ref(''), due=ref<PremiumDuePreview|null>(null), actual=ref(''), slipNo=ref(''), reference=ref(''), method=ref('BANK_TRANSFER'), paidAt=ref(''), message=ref<string|null>(null), error=ref<string|null>(null), loading=ref(false)
const difference=computed(()=>{if(!due.value||!actual.value)return null; const scale=10000n; const parse=(v:string)=>{const [a,b='']=v.split('.');return BigInt(a)*scale+BigInt((b+'0000').slice(0,4))};try{return Number(parse(actual.value)-parse(due.value.calculatedPremiumAmount))/10000}catch{return null}})
async function search(){loading.value=true;error.value=null;try{due.value=await premiumPaymentApi.getDue(applicationNo.value.trim())}catch(e){error.value=e instanceof Error?e.message:'查詢失敗'}finally{loading.value=false}}
async function match(){if(!due.value)return;loading.value=true;error.value=null;message.value=null;try{const r=await premiumPaymentApi.submitAndMatch({applicationNo:due.value.applicationNo,remittanceSlipNo:slipNo.value,paymentMethodCode:method.value,paymentReference:reference.value,currencyCode:due.value.currencyCode,actualPaidAmount:actual.value,paidAt:paidAt.value,payerRelationshipCode:null},crypto.randomUUID());message.value=r.mayUnderwrite?'繳費配對成功，可進入核保承保。':`配對結果：${r.matchStatus}，將產生照會。`}catch(e){error.value=e instanceof Error?e.message:'送金單配對失敗'}finally{loading.value=false}}
</script>
<template><main class="page"><h1>新契約首期保費配對</h1><p class="notice">應繳金額由新契約計算結果帶入，不允許畫面修改；實繳金額以字串傳送，避免浮點誤差。</p><section class="card row"><label>要保書號碼<input v-model="applicationNo" maxlength="32"></label><button :disabled="!applicationNo.trim()||loading" @click="search">查詢應繳</button></section><section v-if="due" class="card"><div class="amount"><span>應繳金額</span><strong>{{ due.currencyCode }} {{ due.calculatedPremiumAmount }}</strong></div><div class="form"><label>送金單號碼<input v-model="slipNo" maxlength="50"></label><label>付款方式<select v-model="method"><option value="BANK_TRANSFER">銀行轉帳</option><option value="CREDIT_CARD">信用卡</option><option value="CASH">現金</option></select></label><label>付款交易參考號<input v-model="reference" maxlength="100"></label><label>實際繳費金額<input v-model="actual" inputmode="decimal" placeholder="12000.0000"></label><label>付款時間<input v-model="paidAt" type="datetime-local"></label><div v-if="difference!==null">差額：{{ due.currencyCode }} {{ difference.toFixed(4) }}</div><button :disabled="loading||!slipNo||!reference||!actual||!paidAt" @click="match">儲存送金單並執行配對</button></div></section><p v-if="message" class="success">{{ message }}</p><p v-if="error" class="error">{{ error }}</p></main></template>
<style scoped>.page{max-width:64rem;margin:2rem auto;padding:0 1rem;font-family:system-ui,sans-serif}.notice{padding:1rem;background:#eef5ff;border-left:4px solid #174ea6}.card{margin:1rem 0;padding:1.25rem;border:1px solid #d7dce5;border-radius:.75rem}.row{display:flex;align-items:end;gap:1rem}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}label{display:grid;gap:.35rem}input,select,button{padding:.7rem;border-radius:.4rem}input,select{border:1px solid #9aa4b2}button{border:0;background:#174ea6;color:white}.amount{display:grid;margin-bottom:1rem}.amount strong{font-size:1.5rem}.success{color:#087443}.error{color:#b42318}@media(max-width:700px){.form{grid-template-columns:1fr}}</style>
