ALTER TABLE new_contract.initial_premium_due COMMENT = '首期保險費應收資料',
  MODIFY COLUMN premium_due_id VARCHAR(36) NOT NULL COMMENT '首期保費應收識別碼',
  MODIFY COLUMN application_no VARCHAR(32) NOT NULL COMMENT '要保書號碼',
  MODIFY COLUMN application_revision BIGINT NOT NULL COMMENT '要保案件版次',
  MODIFY COLUMN currency_code CHAR(3) NOT NULL COMMENT '幣別代碼',
  MODIFY COLUMN calculated_premium_amount DECIMAL(18,4) NOT NULL COMMENT '計算應收保險費金額',
  MODIFY COLUMN calculation_rule_version VARCHAR(50) NOT NULL COMMENT '保費計算規則版本',
  MODIFY COLUMN due_status VARCHAR(20) NOT NULL COMMENT '應收狀態',
  MODIFY COLUMN calculated_at TIMESTAMP(6) NOT NULL COMMENT '保費計算時間',
  MODIFY COLUMN superseded_at TIMESTAMP(6) NULL COMMENT '應收失效時間';

ALTER TABLE new_contract.remittance_slip COMMENT = '首期保險費送金單',
  MODIFY COLUMN remittance_slip_id VARCHAR(36) NOT NULL COMMENT '送金單識別碼',
  MODIFY COLUMN remittance_slip_no VARCHAR(50) NOT NULL COMMENT '送金單號碼',
  MODIFY COLUMN application_no VARCHAR(32) NOT NULL COMMENT '要保書號碼',
  MODIFY COLUMN payment_method_code VARCHAR(20) NOT NULL COMMENT '繳費管道代碼',
  MODIFY COLUMN payment_reference VARCHAR(100) NOT NULL COMMENT '收款交易序號',
  MODIFY COLUMN currency_code CHAR(3) NOT NULL COMMENT '幣別代碼',
  MODIFY COLUMN actual_paid_amount DECIMAL(18,4) NOT NULL COMMENT '實收保險費金額',
  MODIFY COLUMN remittance_status VARCHAR(20) NOT NULL COMMENT '送金單狀態',
  MODIFY COLUMN paid_at TIMESTAMP(6) NOT NULL COMMENT '繳款時間',
  MODIFY COLUMN received_at TIMESTAMP(6) NOT NULL COMMENT '公司收款時間',
  MODIFY COLUMN payer_relationship_code VARCHAR(20) NULL COMMENT '繳款人身分代碼',
  MODIFY COLUMN entered_by VARCHAR(100) NOT NULL COMMENT '送金單登錄人員',
  MODIFY COLUMN created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '資料建立時間';

ALTER TABLE new_contract.initial_premium_match COMMENT = '首期保險費銷帳結果',
  MODIFY COLUMN premium_match_id VARCHAR(36) NOT NULL COMMENT '銷帳結果識別碼',
  MODIFY COLUMN premium_due_id VARCHAR(36) NOT NULL COMMENT '首期保費應收識別碼',
  MODIFY COLUMN remittance_slip_id VARCHAR(36) NOT NULL COMMENT '送金單識別碼',
  MODIFY COLUMN expected_amount DECIMAL(18,4) NOT NULL COMMENT '應收保險費金額',
  MODIFY COLUMN actual_amount DECIMAL(18,4) NOT NULL COMMENT '實收保險費金額',
  MODIFY COLUMN difference_amount DECIMAL(18,4) NOT NULL COMMENT '收付差額',
  MODIFY COLUMN currency_code CHAR(3) NOT NULL COMMENT '幣別代碼',
  MODIFY COLUMN match_status VARCHAR(20) NOT NULL COMMENT '銷帳比對狀態',
  MODIFY COLUMN mismatch_reason_code VARCHAR(32) NULL COMMENT '銷帳不符原因代碼',
  MODIFY COLUMN matched_at TIMESTAMP(6) NOT NULL COMMENT '銷帳比對時間',
  MODIFY COLUMN matched_by VARCHAR(100) NOT NULL COMMENT '銷帳執行人員';

ALTER TABLE new_contract.underwriting_batch_request COMMENT = '新契約批次核保排程案件',
  MODIFY COLUMN batch_request_id VARCHAR(36) NOT NULL COMMENT '批次排程案件識別碼',
  MODIFY COLUMN application_no VARCHAR(32) NOT NULL COMMENT '要保書號碼',
  MODIFY COLUMN requested_business_date DATE NOT NULL COMMENT '指定批次執行日（Asia/Taipei）',
  MODIFY COLUMN request_status VARCHAR(20) NOT NULL COMMENT '排程案件狀態',
  MODIFY COLUMN requested_by VARCHAR(100) NOT NULL COMMENT '排程申請人員',
  MODIFY COLUMN requested_at TIMESTAMP(6) NOT NULL COMMENT '排程申請時間',
  MODIFY COLUMN claimed_by_execution_id VARCHAR(36) NULL COMMENT '領件批次執行識別碼',
  MODIFY COLUMN completed_at TIMESTAMP(6) NULL COMMENT '案件處理完成時間',
  MODIFY COLUMN result_code VARCHAR(32) NULL COMMENT '核保處理結果代碼';

ALTER TABLE new_contract.underwriting_batch_execution COMMENT = '新契約批次核保執行紀錄',
  MODIFY COLUMN batch_execution_id VARCHAR(36) NOT NULL COMMENT '批次執行識別碼',
  MODIFY COLUMN business_date DATE NOT NULL COMMENT '批次執行日（Asia/Taipei）',
  MODIFY COLUMN trigger_type VARCHAR(20) NOT NULL COMMENT '批次觸發方式',
  MODIFY COLUMN execution_status VARCHAR(20) NOT NULL COMMENT '批次執行狀態',
  MODIFY COLUMN started_at TIMESTAMP(6) NOT NULL COMMENT '批次開始時間',
  MODIFY COLUMN completed_at TIMESTAMP(6) NULL COMMENT '批次完成時間',
  MODIFY COLUMN total_count INT NOT NULL DEFAULT 0 COMMENT '總處理件數',
  MODIFY COLUMN approved_count INT NOT NULL DEFAULT 0 COMMENT '承保件數',
  MODIFY COLUMN inquiry_count INT NOT NULL DEFAULT 0 COMMENT '照會件數',
  MODIFY COLUMN failed_count INT NOT NULL DEFAULT 0 COMMENT '失敗件數';
