CREATE DATABASE IF NOT EXISTS new_contract CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS main CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
GRANT ALL PRIVILEGES ON new_contract.* TO 'insurance'@'%';
GRANT SELECT, INSERT, UPDATE ON main.* TO 'insurance'@'%';
FLUSH PRIVILEGES;
